@local = 127.0.0.1:1323

###
GET {{local}}/health
Accept: application/json
Authorization: Bearer xxx

###
GET {{local}}/panic
Accept: application/json
Authorization: Bearer xxx

###
GET {{local}}/api/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMWMxMzk2Y2YtZjJlOC00MWUwLWJjMzktYTM1MzMwNzk4YWNlIiwiZXhwIjoxNzY3ODM3MTc2LCJuYmYiOjE3Njc3NTA3NzYsImlhdCI6MTc2Nzc1MDc3Nn0.0E3F41NWhLFcIMpDu6YPX8-bppmUmRSH3_oDaoDd5rs

###
POST {{local}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "account": "admin@example.com",
  "password": "admin123"
}
