@local = 127.0.0.1:1323

###
GET {{local}}/health
Accept: application/json
Authorization: Bearer xxx

###
GET {{local}}/panic
Accept: application/json
Authorization: Bearer xxx

###
GET {{local}}/api/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJleHAiOjE3NjczMjc2ODksIm5iZiI6MTc2NzI0MTI4OSwiaWF0IjoxNzY3MjQxMjg5fQ.pVJWsvGVs348mZoI4qJdmqQED5NGczaXyGAETtB3A10

###
POST {{local}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "account": "admin@example.com",
  "password": "admin123"
}
