@local = 127.0.0.1:1323

###
GET {{local}}/health
Accept: application/json
Authorization: Bearer xxx

###
GET {{local}}/panic
Accept: application/json
Authorization: Bearer xxx

###
GET {{local}}/api/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTQwYzFlMDEtM2VjNS00MGY4LWEwZTctYmU2NDA2NTUxMzI4IiwiZXhwIjoxNzY3OTI2MjA4LCJuYmYiOjE3Njc5MjYyMDgsImlhdCI6MTc2NzkyNjIwOH0.nM6dNlc0vAWNKRpVydydr1CbeZoT4DGDXghWLHmmZGU

###
POST {{local}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "account": "admin@gosir.com",
  "password": "admin123"
}
